server:
  port: 8761

#spring:
#  application:
#    name: eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      default-zone: http://localhost:8761
  server:
    wait-time-in-ms-when-sync-empty: 5
  serviceUrl:
    defaultZone: http://localhost:8761

